spring:
  application:
    name: tool
  #≈‰÷√ ˝æ›‘¥
  datasource:
    url: jdbc:mysql://localhost:3306/tool?characterEncoding=utf-8&characterSetResults=utf-8&useUnicode=true&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: 8000

## Mybatis ≈‰÷√
mybatis:
  type-aliases-package: com.cf.tool.domain.dto
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.cf.tool.dao: debug